export const CARS = [
  {
    id: 'mustang',
    name: 'Ford Mustang, 2024',
    short: 'Ford Mustang',
    price: 350,
    priceLabel: '350zł / dzień',
    color: '#f5c63a',
    carColor: '#d9a728',
    rating: '4,9',
    ratingNum: 4.9,
    specs: { body: 'Coupe', fuel: 'Benzyna', mileage: '25 700 km', power: '258 KM' },
    reviews: [
      { name: 'Anna', stars: 5, text: 'Obsługa klienta na najwyższym poziomie' },
      { name: 'Marek', stars: 4, text: '' },
    ],
  },
  {
    id: 'audi',
    name: 'Audi Q5 Sportback, 2021',
    short: 'Audi Q5 Sportback',
    price: 230,
    priceLabel: '230zł / dzień',
    color: '#c93a3a',
    carColor: '#9c2828',
    rating: '4,1',
    ratingNum: 4.1,
    specs: { body: 'SUV', fuel: 'Benzyna', mileage: '20 200 km', power: '275 KM' },
    reviews: [
      { name: 'Sebastian', stars: 5, text: 'Auto było super, warte każdej minuty' },
      { name: 'Dmytro', stars: 4, text: 'było dobrze, tylko czegoś brakowało' },
    ],
  },
  {
    id: 'suzuki',
    name: 'Suzuki Ertiga XL7, 2020',
    short: 'Suzuki Ertiga XL7',
    price: 180,
    priceLabel: '180zł / dzień',
    color: '#d04a2f',
    carColor: '#a13620',
    rating: '4,6',
    ratingNum: 4.6,
    specs: { body: 'Minivan', fuel: 'Benzyna', mileage: '34 200 km', power: '103 KM' },
    reviews: [
      { name: 'Iza', stars: 5, text: 'Fajnie auto było' },
      { name: 'Rafał', stars: 4, text: '' },
    ],
  },
  {
    id: 'bmw',
    name: 'BMW 320i, 2023',
    short: 'BMW 320i',
    price: 290,
    priceLabel: '290zł / dzień',
    color: '#2563eb',
    carColor: '#1d4ed8',
    rating: '4,7',
    ratingNum: 4.7,
    specs: { body: 'Sedan', fuel: 'Benzyna', mileage: '12 400 km', power: '184 KM' },
    reviews: [
      { name: 'Kacper', stars: 5, text: 'Świetne prowadzenie, polecam!' },
      { name: 'Monika', stars: 5, text: 'Idealne na dłuższe trasy' },
    ],
  },
  {
    id: 'toyota',
    name: 'Toyota Corolla, 2022',
    short: 'Toyota Corolla',
    price: 200,
    priceLabel: '200zł / dzień',
    color: '#6b7280',
    carColor: '#4b5563',
    rating: '4,5',
    ratingNum: 4.5,
    specs: { body: 'Sedan', fuel: 'Hybryda', mileage: '18 600 km', power: '140 KM' },
    reviews: [
      { name: 'Paweł', stars: 5, text: 'Ekonomiczne i wygodne' },
      { name: 'Agnieszka', stars: 4, text: 'Dobre auto na co dzień' },
    ],
  },
  {
    id: 'mercedes',
    name: 'Mercedes C200, 2023',
    short: 'Mercedes C200',
    price: 320,
    priceLabel: '320zł / dzień',
    color: '#1f2937',
    carColor: '#111827',
    rating: '4,8',
    ratingNum: 4.8,
    specs: { body: 'Sedan', fuel: 'Diesel', mileage: '9 800 km', power: '204 KM' },
    reviews: [
      { name: 'Tomasz', stars: 5, text: 'Luksus w każdym calu' },
      { name: 'Katarzyna', stars: 5, text: '' },
    ],
  },
  {
    id: 'vw',
    name: 'Volkswagen Golf, 2021',
    short: 'VW Golf',
    price: 170,
    priceLabel: '170zł / dzień',
    color: '#059669',
    carColor: '#047857',
    rating: '4,3',
    ratingNum: 4.3,
    specs: { body: 'Hatchback', fuel: 'Benzyna', mileage: '42 100 km', power: '150 KM' },
    reviews: [
      { name: 'Michał', stars: 4, text: 'Solidne auto, nic do zarzucenia' },
      { name: 'Ola', stars: 5, text: 'Kompaktowe i zwrotne w mieście' },
    ],
  },
];

// perDay: true -> billed per rental day; false -> one-time fee
export const EXTRA_OPTIONS = [
  { id: 'delivery',   label: 'Dostawa na miejsce',      price: 49, perDay: false },
  { id: 'childseat',  label: 'Fotelik dziecięcy',       price: 25, perDay: true },
  { id: 'cargo',      label: 'Transport ciężarowy',     price: 79, perDay: false },
  { id: 'twoseat',    label: 'Transport dwumiejscowy',  price: 59, perDay: false },
];
